[package]
name = "dioprocess"
version = "0.0.9"
edition = "2021"

[dependencies]
dioxus = { version = "0.6", features = ["desktop"] }
ui = { path = "../ui" }

[build-dependencies]
embed-resource = "3.0.6"