[package]
name = "dioprocess"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.6", features = ["desktop"] }
tokio = { version = "1", features = ["time"] }
process = { path = "../process" }
