[workspace]
resolver = "2"
members = [
    "crates/process",
    "crates/network",
    "crates/misc",
    "crates/ui",
    "crates/dioprocess",
]

[workspace.package]
version = "0.0.7"
edition = "2021"

