[package]
name = "ui"
version.workspace = true
edition.workspace = true

[dependencies]
dioxus = { version = "0.6", features = ["desktop"] }
tokio = { version = "1", features = ["time"] }
process = { path = "../process" }
arboard = "3"
